### ISSUE TITLE
TODO: 定位任务

### ISSUE THREAD

**Issue by CN-Antonio** [Kepler-2002/CycleQuest#8]
状态：待完成
功能描述：地图中心跳转至所在地理位置，蓝色小圆点为中心
触发条件：①初次启动应用 ②地图界面，点击右上角定位图标

**Comment by Kepler-2002** [comment]
建议是先专注于UI的实现哈，像这样的涉及到业务逻辑的简单功能，还需要core层和service层的配合，这样去实现的话相当于要把core层和service层都进行设计，不算是一个特别高效的实现方式。可以等core层和service层的基础能力就位了之后再去专注于实现业务逻辑

**Comment by CN-Antonio** [comment]
OK

**Comment by CN-Antonio** [comment]
Oh, realized!
